apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Cy1KsS449p3mc1uPC1YM4xxxPj6EYMvqySw5350eQklVRtO7,iv:ZdhkAxBaFKyOKMnzsbioGwEwcobKSyysEqOfgAC00iU=,tag:b5G0LzmAQ7LX3bB3LLczzQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:HfShsNctGQpxj/tkYZ2HACUg3isqj8WofRQFBp+fBwTOcjTUsHHFB4IWcHEdeBeM3H4w14I5otxNhrgK9sjI0ub4tKQ2m3btEPWA/9LiNzzcwHZgr+XqrZYJQxbOWBafkH5sAPH9xM1cbUiVEX+GRJovZuA7YLnZKg6miqD/7A8upW6xW2Q2wE79QyUc/pJIgqQMyeKIEZSfdAHC37JU/Leuh1fm24pLKavH4PYTaA==,iv:a87HbRkTZP0WGzAucOv+zjFuabsXsdPxcSWu6lCkus8=,tag:DpIuuoNeo4/r6/JVaJ25Jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcnqw5dthjhayyq82fkf6d66znt27dvnxgwtzzdav5vck2kx8f4q7tgfth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0d2g2ajVIVU9OVklydnVu
            elhPakJFRFo1ZlJVY2dZSWtOSGc2MFVVeUhNCkRTU2Yxd0hJRHFmaDNiWkRSU0xs
            dFRuL2RDTG9rUXFJbWcvNHFSRkQrV0kKLS0tIHQ1S2JTRzRSTkg2bFloYjlialBl
            cUVEQWZacEhhUUY5TlhiOUNQRUw1SDgKgPUwwio4BsDehT7aKC1/4lzy3fgeePw2
            s035fXtdmJb7bMz5cjUbbdLKFwZZfT3Qejfm2GDBSgikCUBW0Idmgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-22T17:51:05Z"
    mac: ENC[AES256_GCM,data:sgQ6ku24CW2tM5rFAHMBP2eGlfPaGODaI/XE6pYW45D7WHuPxfnBddJpLSwPV+Z0An7+zcToOiu2A7cbvIkTfIFTTA5M0nD3Q592QM3Xj1VF+7xuHdDKumnh9FxQxZ8RpcfvLjVRa6wS7cXhHCu+YH4EAJgh0FwkbCdedUoUKrk=,iv:D7V/l1qeGn4O762/dGvQ4mVv+57xuC0oUq5kNEF9vR8=,tag:j7i9a7oSRS6ZgE3kEgeViA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
