apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:yZLoVrkOCxUDKDbZ9hvZ3GLGyR4gxy41gdSoQZyzq6QLMFWamS2m1A==,iv:SXzrs/LoEo1lwzAzDylj3zEMNvmKhrSTZqkpFteSqTQ=,tag:a0TtxCXoAWSUe7E+ROi+TQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcnqw5dthjhayyq82fkf6d66znt27dvnxgwtzzdav5vck2kx8f4q7tgfth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OFdkc1gvOWZnWlNLZXVF
            SlVlMUNGR0Rhd0RoWjAxZTJ5c0FIb0V1VW5FCmZYL1UzSkJhbFhNQkFyT2d2SnFF
            bUZBYmoyd3d6K3RHQjJSdE5vWFJiYk0KLS0tIEFHd3pJdWxvZ2JSK1lNNTdTMG5h
            OEFpMWpldFVyN0Z4Y2FrVGdPN3hwSXcKbGb4EZsZ+ljChcNza/SA7Ae2Q2c7KHIo
            MQkA2At89MHUAnuF+cGbCw0GXpkvzYr9fmiilBYeubn3X6IV9u9XwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-22T18:57:58Z"
    mac: ENC[AES256_GCM,data:uLiqR32N+2IiJUG1MaktrbWlKWQEgGZ/qhkWnTjo142Xkk9w4GScTOVNal3zAuJqUZVuXgVM2Jgdnj4Sgt5SbnTLak3CzJ89CfKYaa6U8pWmlW0lBniCzCt6nGm1duqYGQ9AmYybQD4Z0+CIx1c8RINGMwV0uB6nbys/qtTp8z4=,iv:3zWi3L5o/0sx5X01QlDuRLKBpeIWYEyKpP1evIsAbDU=,tag:QrpfedIN0BpUGUoR1yc7vQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
