apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:Cwnzd1fEtwUXbkGIgMMOQWB62tQGZ4/i21p9L3QgNImJG97rPqR036InqU5xvn+WvQATHC2hhy7GTtpqKzTID27X5lZTTon+liO0t4PYDmxaUIB3YplfAtYtBiENUw==,iv:69tt0Gz9CXE/yrjZ7GQYaFTIugAfhjoQeXa8M+3OEro=,tag:gbFWiVtilW2JD/QlZCCg7Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:KopMSFs0RPw=,iv:HZjT7ikflPQd2h9AzGIcRaYEAvQKolbSQRglhS7Gtr4=,tag:YIp3LnjN4/joj3RjQe17Fg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:1kjFx/WW+UjBR2A=,iv:HA46wPJ63J2WLSwnZI4FTf9mW1rwLyqWVsx0wsnchJk=,tag:QxnYZCnSRxjw9HksBE4LAg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:BeeWhXTv597OTg1RGT4AMlQusaDvxh4CZks04uqTcSIO074v,iv:OMbuM0FproYWKQicn1gv2MPKKqHM1HOxQj59AVpr2VQ=,tag:7tXCqHAK9saGdlUsPeRp6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcnqw5dthjhayyq82fkf6d66znt27dvnxgwtzzdav5vck2kx8f4q7tgfth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTzR5cll4OGJSR0hZR2Vx
            UzVYUnpjUXZ2b3pOYWR5MXh6VXVVdXlhbTFVCnc2YzFWcmdpV3g0NHh5bUVZa3lW
            YStNeTJTY3lpOVdVNm1UTkJ0UmJyZFEKLS0tIGExN0JFbytadGFMM05KTlMyN0dw
            QkFRWFlYOFZLNjVzZURCUVFCK1duYU0KtKTZPXRMjmcAXo8qLFbqhNdmJl8n0UTn
            YdB9PY9Bi+62PG+8/OAKDjDjdWFpNIWDJLfJWKsC1cPi8yMqECaGjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-22T17:51:05Z"
    mac: ENC[AES256_GCM,data:MBAaRHbXywdeKWtU7JcOHLBgP2zLi5dMEOWiqfOowijzaIw4UtUoVNDOQGSRdhDXz3TE1bUwAxxKnsBeY5sCAG/oTVBA+1S7x5/uuKbY2VFwtUOrXvxeo29Wj67ujitET9YLpqgOgrMgN7PYAsiwT1C2O2yrCA2sFkGPhdUUQns=,iv:IFOZDc77GlIhOOuEf2vNxoSexcIxCMgvbbBlJep5vBw=,tag:MmInDo89f0zEqkFjboiJfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
