apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:PogkW3mIcPWufwnpHoFYbOGZjGPQtMSbNutzt4WwxwY=,iv:yz+kZt6R1q6XWPkSG3E04XCCJg9/hyOtALZQIOE7aFA=,tag:3BXhMS0RUenP/SmOjGbMzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcnqw5dthjhayyq82fkf6d66znt27dvnxgwtzzdav5vck2kx8f4q7tgfth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeHhDQzV1eGdxM1ZYeXA3
            eEJJNDBaVnlnNUtIZmxMbFgzZjc0NHpLN1UwCitiR1hDdE82a0NES2w4RkllN0ZE
            akE3bVNTT3F3MWs3QlRZbFNXUUsxbG8KLS0tIE5lSnNGQmxZSzhITWQva2xHZlBN
            c3MzeVYrNE54dzJyQ3dkdkd4UmdpeTgK1LnZpxOWocHG2YOpcuppWE0MLRGOobkn
            RLMxLCsunciQJmsSWOlH7fd3+D858fQNHveU1Ldd7tprt0GHGxbmdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-22T18:57:58Z"
    mac: ENC[AES256_GCM,data:RXrED6g6p3CviiRGxnveYc3kYXx5X4CCgDQCyFZO/45APBXeQvs/sEWY0XoHX0loXc2hByllmxoeBEBzjcpKLWz6D0YKQoUmmB5IUUysPKVZqkptI4neoSb7RPuM7zhisO5SFOyMHFn2/wTuvLvI+FiD8x2v70SAoX3C+l1TCeM=,iv:HjgPawWqfcJh5XNFWzHeeB8r+Ug0+3qeICYTPn2x69s=,tag:s0A1ARomqY1CyL+PoGgL1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
