apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:jmdK1UFzKuVbIhJcKszM9qLm5Ve5YHfuHopZzQpCHJCsihG1eTcJlw==,iv:56G9oYNAeEoa7OFU5/sy5voCXZT6I7kI2s7YwiGmFIM=,tag:ErtQB4SIeRZtHNQnyM2v1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcnqw5dthjhayyq82fkf6d66znt27dvnxgwtzzdav5vck2kx8f4q7tgfth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOCs4KytpRWZkTFFvUHdn
            cWZCQVpibExEWUlQOHZGUGlGcldmTjdwQ0g4ClhFQkhiTkgrdGtucEZNNklQanFG
            eERFWThFbTZoYVROVzlhVy9FNy85d0EKLS0tIGJFWEQvWllNaWlYOW12SDF3bVdt
            WWFic2JKdGgyQ0hpcVdQNVNSTi9vSW8KjAr7a2Qka3Ta3dTwir7TTF3WOe+hvI94
            u/jgOtcXpppPKaUeFIRaQt3gBhJIBbfsIgeFh9Dxv0kxnuxOV+PI8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-23T16:10:21Z"
    mac: ENC[AES256_GCM,data:jJPaeIO/DlOzwPQQIFuTGFOe3f+Am3yvOfyt0Vk9WPu9+gBOVdywH7i46F4snI7bNqKmkTUKTlaIyK6vknKcxIjyCTHje0P/a+AGWvHbhBFXhBC/xGNNGtFAze2uA7qf5EMcy8mHuDaI5k2ERFmiPwDuizrMhHfdL/+8hFfT42c=,iv:FuVBF9ybriRFeUyCC+ZsKqQ1BHdO1a+WJtjRzDqKjdQ=,tag:itEf9SWE9ubGlZzt/V71dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
